name: Unit Tests
description: "Runs unit tests + linters and optionally gathers coverage."
inputs:
  lint:
    description: 'Whether to run linters.'
    required: false
    default: 'false'
  make-target:
    description: 'The make target to run.'
    required: false
    default: 'test'

runs:
  using: composite
  steps:
    - uses: ./.github/actions/get-go-version
      id: go-version
    - name: Lint
      if: inputs.lint == 'true'
      shell: bash
      run: make lint

    - name: Test
      shell: bash
      id: test
      run: make ${{ inputs.make-target }} | tee raw_report.txt

    - name: Process test results
      if: steps.test.outcome == 'success'
      id: process-test
      shell: bash
      run: go run github.com/jstemmer/go-junit-report@v0.9.1 < raw_report.txt > junit_report.xml

    - name: Upload test results
      if: steps.process-test.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: Test-result-${{ inputs.make-target }}${{ steps.go-version.outputs.version }}
        path: junit_report.xml
