run:
  deadline: 120s
  tests: false

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dupl
    - errcheck
    - goconst
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  fast: false

linters-settings:
  gofmt:
    simplify: false
  goimports:
    local-prefixes: github.com/launchdarkly
  
issues:
  exclude-rules:
    - path: ldvalue/optional_.*.go
      linters:
        - dupl  # This linter would produce false positives due to necessary boilerplate code in ldvalue/optional_*.go
  exclude-use-default: false
  max-same-issues: 1000
  max-per-linter: 1000
