name: Benchmarks
description: "Runs the performance benchmarks."
inputs:
  make-target:
    description: "The make target to run."
    required: true
    default: "benchmarks"

runs:
  using: composite
  steps:
    - uses: ./.github/actions/get-go-version
      id: go-version

    - name: Run Benchmarks
      id: benchmarks
      shell: bash
      run: make ${{ inputs.make-target }} | tee ${{ inputs.make-target}}.txt

    - name: Upload Results
      if: steps.benchmarks.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.make-target }}-${{ steps.go-version.outputs.version }}
        path: ${{ inputs.make-target}}.txt
